apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-app-alert-rules
spec:
  groups:
  - name: app-mon
    rules:
    - alert: too-many-client-connected
      annotations:
        description: 'client connected now: {{ $value }}'
        summary: too many connections
      expr: myapp_client_connected >= 0
      for: 1m
      labels:
        severity: critical 
