apiVersion: v1
kind: Service
metadata:
  name: svc-app
  labels: 
    app: prom-test 
spec:
  selector:
    app: prom-test
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
