apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-external
  namespace: elasticsearch-test
spec:
  version: 8.3.2
  monitoring:
    metrics:
      elasticsearchRefs:
      - secretName: monitoring-metrics-es-ref 
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
