apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  labels:
    app: thanos-receive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
    spec:
      containers:
      - name: thanos-receive
        image: quay.io/thanos/thanos:v0.8.1
        args:
        - receive
        - --tsdb.path=/data/remote-write-receive-data
        - --debug.name=receive       
        - --log.level=debug       
        - --grpc-address=0.0.0.0:19891
        - --http-address=0.0.0.0:18091
        - --remote-write.address=0.0.0.0:19291
        ports:
        - name: http
          containerPort: 19291
        - name: grpc
          containerPort: 19891
