apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos
  name: thanos
spec:
  ports:
  - port: 19291
    protocol: TCP
    targetPort: web
    name: web
  - name: http
    port: 18091
    protocol: TCP
    targetPort: http
  - port: 19891
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos
  type: ClusterIP
